{"name": "Verificar que se permite agregar columnas a la grilla.", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//tbody[@role='presentation']/tr[@class='dx-row dx-data-row'][1]\"}\n  (Session info: chrome=84.0.4147.89)\n\n", "trace": "  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps.py\", line 39, in step_impl\n    context.actions.drag_and_drop(element_1, element_2)\n  File \"C:\\Automatizacion Zulay\\poc\\src\\Actions\\actions.py\", line 61, in drag_and_drop\n    dest_element = self.driver.find_element(*get_locator(dest_element))\n  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given El usuario navega a la página principal", "status": "passed", "attachments": [{"source": "2bc465b7-60fb-4ffb-b56f-af44bd568339-attachment.png", "type": "image/png"}], "start": 1595860375941, "stop": 1595860376640}, {"name": "When El usuario ingrese a la url \"http://192.168.1.105:4200/home/measurement-systems\"", "status": "passed", "attachments": [{"source": "166dd26c-1482-4cfe-ac13-1808469f383e-attachment.png", "type": "image/png"}], "start": 1595860376640, "stop": 1595860377314}, {"name": "When El usuario hace hover en la opción \"MEASUREMENT_SYSTEMS_BTN\"", "status": "passed", "attachments": [{"source": "c18fc682-1c0d-4e7e-a386-0bc2ceb2e1d1-attachment.png", "type": "image/png"}], "start": 1595860377315, "stop": 1595860378006}, {"name": "When El usuario hace hover en la opción \"SERVICE POINTS_BTN\"", "status": "passed", "attachments": [{"source": "47ceffa1-54db-44f2-89d9-8a0ee6d4eb19-attachment.png", "type": "image/png"}], "start": 1595860378007, "stop": 1595860378647}, {"name": "When El usuario de click en la opción \"SELECTOR_COLUMNA\"", "status": "passed", "attachments": [{"source": "50306ffd-8a2a-4051-a1ac-8781b82cc529-attachment.png", "type": "image/png"}], "start": 1595860378648, "stop": 1595860379134}, {"name": "Then El usuario arrastra el objeto \"NEW_COLUMN\" a \"TB_COLUMNAS\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//tbody[@role='presentation']/tr[@class='dx-row dx-data-row'][1]\"}\n  (Session info: chrome=84.0.4147.89)\n\n", "trace": "  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps.py\", line 39, in step_impl\n    context.actions.drag_and_drop(element_1, element_2)\n  File \"C:\\Automatizacion Zulay\\poc\\src\\Actions\\actions.py\", line 61, in drag_and_drop\n    dest_element = self.driver.find_element(*get_locator(dest_element))\n  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1595860379134, "stop": 1595860409231}], "start": 1595860375940, "stop": 1595860409233, "uuid": "50bc694a-f40f-42af-a6e7-315c811d1c2f", "historyId": "b214a1bf9bac3471ce406a0fb470d1b1", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "5500-3"}, {"name": "tag", "value": "UI"}, {"name": "feature", "value": "5191 - Sistemas de medición"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}