{"name": "Verificar que se permite agregar columnas a la grilla.", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//tbody[@role='presentation']/tr[@class='dx-row dx-data-row'][1]\"}\n  (Session info: chrome=84.0.4147.89)\n\n", "trace": "  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps.py\", line 39, in step_impl\n    context.actions.drag_and_drop(element_1, element_2)\n  File \"C:\\Automatizacion Zulay\\poc\\src\\Actions\\actions.py\", line 61, in drag_and_drop\n    dest_element = self.driver.find_element(*get_locator(dest_element))\n  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given El usuario navega a la página principal", "status": "passed", "attachments": [{"source": "e2a969e1-ad11-450a-a27a-c84779a9a9b6-attachment.png", "type": "image/png"}], "start": 1595860728155, "stop": 1595860728840}, {"name": "When El usuario ingrese a la url \"http://192.168.1.105:4200/home/measurement-systems\"", "status": "passed", "attachments": [{"source": "ef8923e0-9ac0-4aba-bd59-00620d4d1267-attachment.png", "type": "image/png"}], "start": 1595860728841, "stop": 1595860729432}, {"name": "When El usuario hace hover en la opción \"MEASUREMENT_SYSTEMS_BTN\"", "status": "passed", "attachments": [{"source": "7ded3c90-fa5b-4713-8cc3-8b57862ddaac-attachment.png", "type": "image/png"}], "start": 1595860729432, "stop": 1595860730106}, {"name": "When El usuario hace hover en la opción \"SERVICE POINTS_BTN\"", "status": "passed", "attachments": [{"source": "bd6ceefe-6836-4ac9-903b-4c1d019b7b68-attachment.png", "type": "image/png"}], "start": 1595860730106, "stop": 1595860730726}, {"name": "When El usuario de click en la opción \"SELECTOR_COLUMNA\"", "status": "passed", "attachments": [{"source": "cb29f19a-d8cc-4e11-bfb8-a38b84070ec6-attachment.png", "type": "image/png"}], "start": 1595860730727, "stop": 1595860731300}, {"name": "Then El usuario arrastra el objeto \"NEW_COLUMN\" a \"TB_COLUMNAS\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//tbody[@role='presentation']/tr[@class='dx-row dx-data-row'][1]\"}\n  (Session info: chrome=84.0.4147.89)\n\n", "trace": "  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps.py\", line 39, in step_impl\n    context.actions.drag_and_drop(element_1, element_2)\n  File \"C:\\Automatizacion Zulay\\poc\\src\\Actions\\actions.py\", line 61, in drag_and_drop\n    dest_element = self.driver.find_element(*get_locator(dest_element))\n  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\jose.carpintero\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1595860731300, "stop": 1595860761373}], "start": 1595860728154, "stop": 1595860761375, "uuid": "3f936236-8337-480f-83d4-a1573b7cd27a", "historyId": "b214a1bf9bac3471ce406a0fb470d1b1", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "5500-3"}, {"name": "tag", "value": "UI"}, {"name": "feature", "value": "5191 - Sistemas de medición"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}